
language: go

go:
  - "1.15.x"
  - "1.14.x"
  - "1.13.x"
  - master

env:
  - GO111MODULE=on

script:
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)